[project]
name = "untangle"
version = "0.0.0"
description = "Python package for decoupling multivariate functions using tensor decompositions."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
